name: Build Flatpak

on:
  push:
    branches: [master]
  pull_request:

jobs:
  flatpak:
    name: Build Flatpak Bundle
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run dependency download
        run: python3 download_dependencies.py

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: dev.seelos.drucken3d.json
          bundle: stratum.flatpak
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true
