name: Windows Build (Meson GTK4 Libadwaita)

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: >-
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-python-pip
            mingw-w64-ucrt-x86_64-python-gobject
            mingw-w64-ucrt-x86_64-gtk4
            mingw-w64-ucrt-x86_64-libadwaita
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-desktop-file-utils
            mingw-w64-ucrt-x86_64-gettext
            mingw-w64-ucrt-x86_64-itstool
            mingw-w64-ucrt-x86_64-glib2
            mingw-w64-ucrt-x86_64-gdal
            mingw-w64-ucrt-x86_64-python-gdal
            mingw-w64-ucrt-x86_64-python-pillow
            mingw-w64-ucrt-x86_64-python-numpy
            mingw-w64-ucrt-x86_64-python-matplotlib
            mingw-w64-ucrt-x86_64-python-scikit-image
            mingw-w64-ucrt-x86_64-python-shapely
            mingw-w64-ucrt-x86_64-python-trimesh
            zip

      - name: Install Dependencies
        shell: msys2 {0}
        run: |
          export GDAL_VERSION=$(gdal-config --version)
          echo "Detected GDAL_VERSION=$GDAL_VERSION"
          pip install -r requirements.txt

      - name: Configure and build with Meson
        shell: msys2 {0}
        run: |
          meson setup builddir --prefix="$PWD/build-install"
          meson compile -C builddir
          meson install -C builddir

      - name: Install PyInstaller and build EXE
        shell: msys2 {0}
        run: |
          pip install pyinstaller
          pyinstaller stratum.spec

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: drucken3d-windows
          path: dist/drucken3d


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-windows
          path: my-app-windows.zip
